version: '3'
services:
  web:
    build: .
    ports:
    - "8080:80"
  mysql:
    image: "mysql:latest"
    ports:
    - "3306:3306"
    environment:
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=dbpassword
    - MYSQL_ROOT_PASSWORD=rootpassword
    - MYSQL_DATABASE=devdb